- name: copy scripts
  action: copy src=../files/{{ item.path }} dest=/usr/bin/{{ item.dest }}
  with_items:
    - { path: 'base_config', dest: 'base_config', mode: 0655 }
    - { path: 'base_functions', dest: 'base_functions', mode: 0655 }
    - { path: 'git_branch', dest: 'git_branch', mode: 0655 }
    - { path: 'git_merge', dest: 'git_merge', mode: 0655 }
    - { path: 'git_pull', dest: 'git_pull', mode: 0655 }
    - { path: 'ws_restart', dest: 'ws_restart', mode: 0655 }
    - { path: 'link_configs', dest: 'link_configs', mode: 0655 }
