- name: copy scripts
  action: copy src=../files/{{ item.path }} dest=/usr/bin/{{ item.dest }} mode={{item.mode}}
  with_items:
    - { path: 'base-config', dest: 'base-config', mode: 655 }
    - { path: 'base-functions', dest: 'base-functions', mode: 655 }
    - { path: 'git-branch', dest: 'git-branch', mode: 655 }
    - { path: 'git-merge', dest: 'git-merge', mode: 655 }
    - { path: 'git-pull', dest: 'git-pull', mode: 655 }
    - { path: 'ws-restart', dest: 'ws-restart', mode: 655 }
    - { path: 'link-configs', dest: 'link-configs', mode: 655 }

- name: add php tools
  action: get_url url={{item.url}} dest=/usr/local/bin/{{item.dest}} mode={{item.mode}} force=yes validate_certs=no
  with_items:
    - { url: 'https://phar.phpunit.de/phpunit.phar', dest: 'phpunit', mode: '555' }
    - { url: 'https://phar.phpunit.de/phploc.phar', dest: 'phploc', mode: '555' }
    - { url: 'https://phar.phpunit.de/phpcpd.phar', dest: 'phpcpd', mode: '555' }
    - { url: 'https://getcomposer.org/composer.phar', dest: 'composer', mode: '555' }
    - { url: 'https://phar.phpunit.de/phpdcd.phar', dest: 'phpcd', mode: '555' }
    - { url: 'https://github.com/Halleck45/PhpMetrics/raw/master/build/phpmetrics.phar', dest: 'metrics', mode: '555' }
