---
- name: restart smbd
  service: name=smbd state=restarted

- name: restart nginx
  service: name=nginx state=restarted

- name: restart php-fpm
  service: name=php5-fpm state=restarted

- name: restart mariadb
  service: name=mysql state=restarted