- name: add/check repository
  apt_repository: repo='deb http://mirror2.hs-esslingen.de/mariadb/repo/10.0/debian wheezy main' state=present

- name: update repositories
  action: command /usr/bin/apt-get update

- name: install packages
  action: apt pkg={{item}} state=latest
  with_items:
    - mariadb-server
    - mariadb-client
    - mariadb-common

- name: start server
  service: name=mysql state=started enabled=true

- name: configure the root credentials
  action: command mysqladmin -u root password vagrant