---
- name: Update repository
  apt: update_cache=yes cache_valid_time=3600

- name: install mariadb packages
  action: apt pkg={{item}} state=latest
  with_items:
    - mariadb-server
    - mariadb-client
    - mariadb-common
  notify: start mysql

- name: Install config file for network settings
  template:
    src: etc_my.cnf.d_network.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/network.cnf
  notify: restart mysql

- name: Update root password
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{mysql_root_pw}}"
    state: present
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  ignore_errors: yes
  notify: restart mysql

- name: create my.cnf
  template: src=./my.cnf.j2 dest="~/.my.cnf"

- name: ensure vagrant user exists
  mysql_user: name={{mysql_vagrant_user}} password={{mysql_vagrant_user}} priv=*.*:ALL,GRANT state=present login_unix_socket=/var/run/mysqld/mysqld.sock

- name: install elasticsearch packages
  action: apt pkg={{item}} state=latest
  with_items:
    - openjdk-7-jre-headless
    - elasticsearch
