#!/bin/bash

source /usr/bin/base-config
source /usr/bin/base-functions

# define files and paths
FILES=( "git-merge" "git-pull" "git-branch" "ws-restart" "link-configs" )
SCRIPT_PATH=$CONFIG_BASE_SCRIPT_PATH
TARGET_PATH="/usr/bin/"

echo "checking for symlinks..."
echo ""
# iterate files array
for FILE in "${FILES[@]}"
do
#check if symlink already exists
	if [ ! -h ${TARGET_PATH}${FILE} ]
	then
        #otherwise create ;-)
		echo "creating symlink for ${FILE}..."
		sudo ln -s ${SCRIPT_PATH}/${FILE} ${TARGET_PATH}${FILE}
	else
	    echo "${FILE} already exists."
	fi
done
echo ""
echo "... done!"
