#!/bin/bash

source /usr/bin/base-config
source /usr/bin/base-functions

TITLE=$(cat <<DELIMITER
stashes changes, pulls current version, pops stash
DELIMITER
)

logo "${TITLE}"

echo "------------------------------------------------------"
echo ""
echo "stashing our changes... "
echo ""
git stash save -q
echo "pulling (--rebase) current branch state... "
echo ""
git pull --rebase
echo "popping your stash again ;-)"
echo ""
git stash pop -q
echo "done!"
