- name: copy files
  copy: src=../files/{{item.path}} dest={{item.dest}} mode={{item.mode}} owner={{item.owner}} group={{item.group}}
  with_items:
    - { path: '.bashrc', dest: '/root/.bashrc', owner: root, group: root, mode: 600 }
    - { path: '.bashrc', dest: '/home/vagrant/.bashrc', owner: vagrant, group: vagrant, mode: 600 }

- name: add/check wheezy stable
  apt_repository: repo='deb http://ftp.de.debian.org/debian stable main contrib non-free' state=present

- name: add/check wheezy updates
  apt_repository: repo='deb http://ftp.debian.org/debian/ wheezy-updates main contrib non-free' state=present

- name: add/check wheezy security updates
  apt_repository: repo='deb http://security.debian.org/ wheezy/updates main contrib non-free' state=present

- name: add/check wheezy backports
  apt_repository: repo='deb http://ftp.us.debian.org/debian wheezy-backports main' state=present

# Update the repo, because most boxes are heavily outdated
- name: Update repository
  action: command /usr/bin/apt-get update

- name: Upgrade repository
  action: command apt-get -y dist-upgrade

- name: install syspackages
  action: apt pkg={{item}} state=latest
  with_items:
    - molly-guard
    - logrotate
    - vim
    - curl
    - git
    - git-ftp
    - strace
    - sysstat
    - build-essential
    - wget
    - bash-completion
    - ntp
    - ntpdate
    - unzip
    - bzip2
    - zip
    - samba
    - samba-common
    - smbclient
    - sendmail
    - sendmail-bin
    - python
    - python-pip
    - python-dev
    - python-software-properties
    - python-mysqldb
    - nodejs
