---
- name: copy files
  copy: src=../files/{{item.path}} dest={{item.dest}} mode={{item.mode}} owner={{item.owner}} group={{item.group}}
  with_items:
    - { path: '.bashrc', dest: '/root/.bashrc', owner: root, group: root, mode: 600 }
    - { path: '.bashrc', dest: '/home/vagrant/.bashrc', owner: vagrant, group: vagrant, mode: 600 }
    - { path: 'hosts', dest: '/etc/hosts', owner: root, group: root, mode: 666 }
    - { path: 'my.cnf', dest: '~/.my.cnf', owner: root, group: root, mode: 644 }
    #- { path: 'motd', dest: '/etc/motd', owner: root, group: root, mode: 644 }
    #- { path: 'motd', dest: '/etc/motd.tail', owner: root, group: root, mode: 644 }

- name: add repositories
  action: apt_repository repo="deb {{item}}" state=present
  with_items:
    - "http://ubuntu.mirror.lrz.de/ubuntu vivid main restricted universe multiverse"
    - "http://ubuntu.mirror.lrz.de/ubuntu vivid-updates main restricted universe multiverse"
    - "http://ubuntu.mirror.lrz.de/ubuntu vivid-security main restricted universe multiverse"

- name: Update repository
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrade repository
  apt: upgrade=dist force=yes

- name: Cleanup
  action: command apt-get autoclean

- name: Remove old packages
  action: command apt-get -y autoremove

- name: install syspackages
  action: apt pkg={{item}} state=latest
  with_items:
    - molly-guard
    - logrotate
    - vim
    - curl
    - git
    - git-flow
    - strace
    - sysstat
    - sshfs
    - build-essential
    - wget
    - bash-completion
    - ntp
    - ntpdate
    - unzip
    - bzip2
    - zip
    - samba
    - samba-common
    - smbclient
    - sendmail
    - sendmail-bin
    - python
    - python-pip
    - python-dev
    - python-software-properties
    - python-mysqldb