# copy needed files
- name: Common | copy files
  action: copy src=../files/{{ item.path }} dest={{ item.dest }} state=file
  with_items:
    - { path: 'sources.list', dest: '/etc/apt/sources.list', mode: 0644 }
    - { path: 'dotdeb.sources.list', dest: '/etc/apt/sources.list.d/dotdeb.sources.list', mode: 0644 }
    - { path: '.bashrc', dest: '/root/.bashrc', mode: 0600 }
    - { path: '.bashrc', dest: '/home/vagrant/.bashrc', owner: vagrant, group: vagrant, mode: 0600 }

# Update the repo, because most boxes are heavily outdated
- name: Commmon | Update repository
  action: command /usr/bin/apt-get update

- name: Commmon | Upgrade repository
  action: command apt-get -y dist-upgrade

- name: Common | install syspackages
  action: apt pkg={{item}} state=installed
  with_items:
    - molly-guard
    - logrotate
    - vim
    - curl
    - git 
    - strace
    - sysstat
    - build-essential
    - wget
    - bash-completion
    - ntp
    - ntpdate
    - unzip
    - bzip2
    - zip
    - samba
    - samba-common
    - smbclient
    - sendmail
    - sendmail-bin
    - python
    - python-pip
    - python-dev
    - python-software-properties
