- name: add sudoadmin group
  action: group name={{item}} state=present
  with_items:
    - sudoadmin
    - sudoers
    - developers

# first create home directory
- name: create home directory {{user_home_base}}/{{user}}
  action: file path={{user_home_base}}/{{user}}/.ssh state=directory owner={{user}} group={{user}}

# add user and group stuff
- name: add {{user}} and home {{user_home_base}}/{{user}}
  action: user name={{user}} shell=/bin/bash groups=sudoadmin append=yes home={{user_home_base}}/{{user}} state=present

# change owner and goup for user directory
- name: create home directory {{user_home_base}}/{{user}}
  action: file path={{user_home_base}}/{{user}} group={{user}} owner={{user}}

# copy all files needed for a user to his homediir
- name: copy user files
  action: copy src=../files{{ item.path }} dest={{user_home_base}}/{{user}}{{ item.dest }} owner={{user}} group={{user}}
  with_items:
    - { path: '/.bashrc', dest: '/.bashrc', mode: 0644 }
    - { path: '/.gitconfig', dest: '/.gitconfig', mode: 0644 }
    - { path: '/.gitignore_global', dest: '/.gitignore_global', mode: 0644 }
    - { path: '/.vimrc', dest: '/.vimrc', mode: 0644 }
    - { path: '/authorized_keys', dest: '/.ssh/authorized_keys', mode: 0600 }
    - { path: '/ssh_config', dest: '/.ssh/ssh_config', mode: 0600 }

- name: copy smb.conf
  action: copy src=../files/smb.conf dest=/etc/samba/smb.conf owner=root group=root
  notify: restart smbd