- name: uninstall packages if present
  action: apt pkg={{item}} state=absent
  with_items:
    - php-apc

- name: install common
  action: apt pkg={{item}} state=latest force=yes
  with_items:
    - php5-fpm
    - php5-common
    - php5-cli

- name: install additional packages
  action: apt pkg={{item}} state=latest force=yes
  with_items:
    - php5-apcu
    - php5-curl
    - php5-gd
    - php5-imagick
    - php5-mcrypt
    - php5-memcache
    - php5-mysql
    - php5-xdebug
    - php-pear
    - php5-intl
    - php5-dev
    - phpunit
    - mcrypt

# copy all files needed for a user to his homediir
- name: copy configs
  action: copy src=../files/{{item.path}} dest=/etc/php5/{{item.dest}} mode={{item.mode}}
  with_items:
    - { path: 'custom.xdebug.ini', dest: 'fpm/conf.d/99-custom.xdebug.ini', mode: 644 }
    - { path: 'custom.opcache.ini', dest: 'fpm/conf.d/99-custom.opcache.ini', mode: 644 }
    - { path: 'custom.cli.opcache.ini', dest: 'cli/conf.d/99-custom.opcache.ini', mode: 644 }
    - { path: 'dev.local.conf', dest: 'fpm/pool.d/dev.local.conf', mode: 644 }

- name: create custom configs
  template: src=../files/{{item.src}} dest=/etc/php5/{{item.dest}} owner=root group=root mode={{item.mode}}
  with_items:
    - { src: 'custom.php.ini', dest: 'fpm/conf.d/99-custom.php.ini', mode: 644 }
    - { src: 'custom.cli.php.ini', dest: 'cli/conf.d/99-custom.php.ini', mode: 644 }

- name: remove default configs
  file: path=/etc/php5/fpm/pool.d/www.conf state=absent
  notify: restart php-fpm

- name: create slowlog dir
  file: path=/var/log/php-fpm/ state=directory
  notify: start php-fpm
