---
- hosts: devbox-15-04
  sudo: True
  roles:
    - common
    - user
    #- nginx
    - { role: geerlingguy.nginx }
    - nginx-common
    - php
    #- { role: geerlingguy.php }
    - mongodb
    - db
    - { role: geerlingguy.adminer }
    - tools
    - ansible

  vars_files:
    - "group_vars/devbox-15-04"