---
# This playbook will set up a vagrant box for generic LAMP development.
# See the various roles (especially roles/*/tasks/main.yml) for more details.

# Looks for the [vagrant] section in the hosts file to determine which machines
# to operate on.
- hosts: devbox
  sudo: True
  # Looks for roles/{role}/tasks/main.yml for tasks, roles/{role}/handlers/main.yml  
  # for handlers, etcetera.
  roles:
    - common
    - php
    - db
    - tools