---
- hosts: devbox-15-04
  sudo: True
  vars_files:
    - vars/main.yml
  roles:
    - common
    #- user
    #- nginx
    #- php
    #- mongodb
    #- db
    - { role: geerlingguy.mysql }
    #- { role: geerlingguy.adminer }
    #- adminer-custom
    #- tools
    #- ansible

  vars_files:
    - "group_vars/devbox-15-04"